language: r
sudo: false
cache: false

r:
  - oldrel
  - release

os:
  - osx

script:
  - Rscript -e "rmarkdown::render('examples/lecture-09.Rmd')"
  - Rscript -e "rmarkdown::render('extras/lecture-09-extras-joins.Rmd')"
  